### PR TITLE
adding optional flow and tcomb type annotation checks (dev only)

### PR DESCRIPTION
**Pull request by jefffriesen**
Not sure if you're interested in using typechecking  with Flowtypes (https://flowtype.org). If not no worries. If so, that's great.

I used tcomb's implementation (https://github.com/gcanti/babel-plugin-tcomb) instead of the more obvious one (https://github.com/codemix/babel-plugin-typecheck) because the latter seems to be neglected at this point.  tcomb's babel plugin is fully compatible with both Flowtype and tcomb's type annotations.

### CODE REVIEW

**Comment by pavanpodila** [comment]
I think its good to have this support. Will need more documentation in the Readme to talk about how to enable it. I think by default it should be turned off so as not to be too overwhelming. What do you say?

**Comment by jefffriesen** [comment]
@pavanpodila Let me know what you think of the documentation addition I just made. 

Since it's gradual typing, it won't check types unless you add types. In theory there is a little overhead in that for babel, but I've never noticed. The only way I can think of having it really off by default is  commenting out this line in `.babelrc` https://github.com/jefffriesen/react-mobx-seed/blob/flowtypes/.babelrc#L15.

So I guess there are two approaches:
1. Comment out the type checking plugin and not have an example in the code of type-check functions (like I have here https://github.com/jefffriesen/react-mobx-seed/blob/flowtypes/src/clock/clock.store.js#L19)
2. Leave the type checking on for all users and let them comment it out if they really don't want it. 

Seems like either is fine. Over this past year of using type checking it has been such a huge help, catching multiple potential bugs per day. It feels like a new language. So I would lean towards encouraging it, but I'm really not attached to how we implement it here.

**Comment by pavanpodila** [comment]
I like keeping it and giving them the Readme to decide how they want to use it. Your readme section looks good. I would also include a quick one-liner to tell them how it can be turned off (if they want to).

Also looks like there are some conflicts in `.babelrc`

**Comment by jefffriesen** [comment]
@pavanpodila 
Ok, conflict is resolved. I had a line in there about how to turn off type checking completely, but it was combined with another paragraph. Now it's on it's own line and more scannable.

**Pull request merged**
